In [1]:
cd ..

/home/mscs/congfeng4/GuidedStudy/Code/SCOIT


/public/congfeng4/miniconda3/envs/py39/lib/python3.9/site-packages/IPython/core/magics/osm.py:417: UserWarning: using dhist requires you to install the `pickleshare` library.
  self.shell.db['dhist'] = compress_dhist(dhist)[-100:]


In [2]:
import numpy as np

In [3]:
train_data = np.load('./data/GPS/train_data.npz', allow_pickle=True)

In [4]:
train_data.keys()

KeysView(<numpy.lib.npyio.NpzFile object at 0x7f75ec0fef10>)

In [5]:
train_data['train_data']

array([[ 93,  57,   4],
       [ 17,   7,   0],
       [ 26,  13,   4],
       ...,
       [108,  15,   1],
       [113,   1,   0],
       [141,  41,   3]])

In [6]:
train_data['nums_type']

array([146,  70,   5])

In [7]:
test_data = np.load('./data/GPS/test_data.npz', allow_pickle=True)

In [8]:
test_data

In [9]:
test_data['nums_type']

array([146,  70,   5])

In [10]:
from hgnn.hypergraph import *

## Convert all graphs to Hyper_SAGNN format.

In [ ]:
TRAIN_SIZE = 0.9

for subdir in Path('./hypergraph').iterdir():
    if not subdir.is_dir():
        continue
    try:
        hg = load_graph(subdir)
    except Exception as e:
        print('Failed to load', subdir, 'except', e)
        continue
    convert_to_hypersagnn_format(hg, TRAIN_SIZE, subdir)


In [ ]:
TRAIN_SIZE = 0.9

for subdir in Path('./hypergraph').iterdir():
    if not subdir.is_dir():
        continue
    try:
        hg = load_graph(subdir)
    except Exception as e:
        print('Failed to load', subdir, 'except', e)
        continue
    convert_to_hypersagnn_format(hg, TRAIN_SIZE, subdir)


Load edges in 0.00 seconds.
Load nodes in 0.00 seconds.
Num nodes: 287, Num edges: 6805
Metadata: {'dataname': 'sc_GEM', 'filter_edge': 'non-negative', 'num_cells': 224, 'num_genes': 61, 'num_omics': 2, 'num_nodes': 287, 'orig_edges': 13664, 'num_edges': 6805, 'omics_offset': 0, 'gene_offset': 2, 'cell_offset': 63, 'raw_data': {'expr': './data/sc_GEM/expression_data.csv', 'methy': './data/sc_GEM/methylation_data.csv'}, 'cell_key': 'Cell ID'}
nums_type [224, 61, 2]
num_edges 6805
train_data (6124, 3) train_weight (6124,) test_data (681, 3) test_weight (681,)
Save to /public/congfeng4/hypergraph/sc_GEM
Load edges in 0.00 seconds.
Load nodes in 0.00 seconds.
Num nodes: 378, Num edges: 9977
Metadata: {'dataname': 'PEA_STA', 'filter_edge': 'non-negative', 'num_cells': 210, 'num_genes': 166, 'num_omics': 2, 'num_nodes': 378, 'orig_edges': 34860, 'num_edges': 9977, 'omics_offset': 0, 'gene_offset': 2, 'cell_offset': 168, 'raw_data': {'expr': './data/PEA_STA/expression_data.csv', 'protein': '.