In [1]:
cd ..

/Users/fengcong/Desktop/0825-course/Guided Study/Code/SCOIT


In [2]:
import numpy as np

In [3]:
train_data = np.load('./data/GPS/train_data.npz', allow_pickle=True)

In [4]:
train_data.keys()

KeysView(NpzFile './data/GPS/train_data.npz' with keys: nums_type, train_data)

In [5]:
train_data['train_data']

array([[ 93,  57,   4],
       [ 17,   7,   0],
       [ 26,  13,   4],
       ...,
       [108,  15,   1],
       [113,   1,   0],
       [141,  41,   3]])

In [6]:
train_data['nums_type']

array([146,  70,   5])

In [7]:
test_data = np.load('./data/GPS/test_data.npz', allow_pickle=True)

In [8]:
test_data

NpzFile './data/GPS/test_data.npz' with keys: test_data, nums_type

In [9]:
test_data['nums_type']

array([146,  70,   5])

In [10]:
from hgnn.hypergraph import *

In [11]:
hg = load_graph('./hypergraph/sc_GEM')

Load edges in 0.00 seconds.
Load nodes in 0.00 seconds.
Num nodes: 287, Num edges: 6805
Metadata: {'dataname': 'sc_GEM', 'filter_edge': 'non-negative', 'num_cells': 224, 'num_genes': 61, 'num_omics': 2, 'num_nodes': 287, 'num_edges': 6805, 'omics_offset': 0, 'gene_offset': 2, 'cell_offset': 63, 'raw_data': {'expr': './data/sc_GEM/expression_data.csv', 'methy': './data/sc_GEM/methylation_data.csv'}, 'cell_key': 'Cell ID'}


In [12]:
convert_to_hypersagnn_format(hg, train_size=0.9, save_dir='./hypergraph/sc_GEM')

nums_type [224, 61, 2]
num_edges 6805
train_data (6124, 3) train_weight (6124,) test_data (681, 3) test_weight (681,)
Save to hypergraph/sc_GEM


In [13]:
train_data = np.load('./hypergraph/sc_GEM/train_data.npz', allow_pickle=True)
train_data

NpzFile './hypergraph/sc_GEM/train_data.npz' with keys: train_data, train_weight, nums_type

In [14]:
test_data = np.load('./hypergraph/sc_GEM/test_data.npz', allow_pickle=True)
test_data

NpzFile './hypergraph/sc_GEM/test_data.npz' with keys: test_data, test_weight, nums_type

In [15]:
train_data['train_data']

array([[121,  27,   0],
       [ 64,  12,   0],
       [168,  56,   1],
       ...,
       [131,   9,   0],
       [ 81,  55,   1],
       [107,  14,   0]])

In [16]:
td = train_data['train_data']

print('min', np.min(td, 0))
print('max', np.max(td, 0))
print(train_data['nums_type'])

min [0 0 0]
max [223  60   1]
[224  61   2]


## Convert all graphs to Hyper_SAGNN format.

In [17]:
TRAIN_SIZE = 0.9

for subdir in Path('./hypergraph').iterdir():
    if not subdir.is_dir():
        continue
    try:
        hg = load_graph(subdir)
    except Exception as e:
        print('Failed to load', subdir, 'except', e)
        continue
    convert_to_hypersagnn_format(hg, TRAIN_SIZE, subdir)


Load edges in 0.02 seconds.
Load nodes in 0.01 seconds.
Num nodes: 10411, Num edges: 14504
Metadata: {'dataname': 'SNARE_seq_adult_mouse', 'filter_edge': '3-sigma', 'num_cells': 10309, 'num_genes': 100, 'num_omics': 2, 'num_nodes': 10411, 'num_edges': 14504, 'omics_offset': 0, 'gene_offset': 2, 'cell_offset': 102, 'raw_data': {'atac': './data/SNARE_seq_adult_mouse/ATAC_lsi.csv', 'rna': './data/SNARE_seq_adult_mouse/RNA_pca.csv'}, 'cell_key': 'Unnamed: 0'}
nums_type [10309, 100, 2]
num_edges 14504
train_data (13053, 3) train_weight (13053,) test_data (1451, 3) test_weight (1451,)
Save to hypergraph/SNARE_seq_adult_mouse
Load edges in 0.00 seconds.
Load nodes in 0.00 seconds.
Num nodes: 287, Num edges: 6805
Metadata: {'dataname': 'sc_GEM', 'filter_edge': 'non-negative', 'num_cells': 224, 'num_genes': 61, 'num_omics': 2, 'num_nodes': 287, 'num_edges': 6805, 'omics_offset': 0, 'gene_offset': 2, 'cell_offset': 63, 'raw_data': {'expr': './data/sc_GEM/expression_data.csv', 'methy': './data/sc